version: "3.9"
services:
  database:
    container_name: database
    user: root
    image: postgres:13.3-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - movies-network

  pgadmin:
    container_name: pgadmin
    user: root
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: jamie@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    links:
      - database:pgsql-server
    networks:
      - movies-network

  movies-service:
    image: movies-service
    container_name: movies-service
    build: 
      context: movies_service
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - database
    ports:
      - 8001:8001
    env_file:
      - ./movies_service/.env
    volumes:
      - ./movies_service:/app
    networks:
      - movies-network

volumes:
  database:
  pgadmin:
  movies-service:

networks:
  movies-network:
    driver: bridge
